
package musiconweb;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.*;
import javax.swing.JOptionPane;
import model.SalesHistory;
/**
 *
 * @author AmTechGuy
 */
public class DashBoard extends javax.swing.JFrame {
    
    public static String email;
    private Clip clip;
    /**
     * Creates new form DashBoard
     * @param email
     */
    public DashBoard(String email) {
        initComponents();
        DashBoard.email = email;
        
        btnPlay.setFocusable(false);
        btnPause.setFocusable(false);
        
        if(!email.equals("raji@gmail.com")){
             lblManageCategory.setVisible(false);
            lblNewMusic.setVisible(false);
//            lblManageCategory.setVisible(true);
//            lblNewMusic.setVisible(true);
        }
    }
    
    public void musicPlayer(String path){
    
     try{
            File file = new File(path);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(audioStream);
            clip.start();
            
        
        }
        catch(UnsupportedAudioFileException | IOException | LineUnavailableException exception){
            //JOptionPane.showMessageDialog(null, "Error");
            exception.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNewMusic = new javax.swing.JLabel();
        lblChangePassword = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblPlaceOrder = new javax.swing.JLabel();
        lblViewOrderPlaced = new javax.swing.JLabel();
        lblManageCategory = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 235, 215));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Music DashBoard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 61, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/music1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 19, -1, 137));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNewMusic.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNewMusic.setForeground(new java.awt.Color(255, 255, 255));
        lblNewMusic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        lblNewMusic.setText("New Music");
        lblNewMusic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewMusicMouseClicked(evt);
            }
        });
        jPanel2.add(lblNewMusic, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 27, -1, -1));

        lblChangePassword.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        lblChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Security Question.png"))); // NOI18N
        lblChangePassword.setText("Change Password");
        jPanel2.add(lblChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 27, -1, -1));

        lblLogout.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        jPanel2.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 27, -1, -1));

        lblPlaceOrder.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        lblPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        lblPlaceOrder.setText("Place Order");
        lblPlaceOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlaceOrderMouseClicked(evt);
            }
        });
        jPanel2.add(lblPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 27, -1, -1));

        lblViewOrderPlaced.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblViewOrderPlaced.setForeground(new java.awt.Color(255, 255, 255));
        lblViewOrderPlaced.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View Bills & Order Placed Details.png"))); // NOI18N
        lblViewOrderPlaced.setText("View Order Placed");
        lblViewOrderPlaced.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewOrderPlacedMouseClicked(evt);
            }
        });
        jPanel2.add(lblViewOrderPlaced, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 27, -1, -1));

        lblManageCategory.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblManageCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblManageCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category.png"))); // NOI18N
        lblManageCategory.setText("Manage Category");
        lblManageCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageCategoryMouseClicked(evt);
            }
        });
        jPanel2.add(lblManageCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 27, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 1230, 90));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("02 Davido - FEEL (NetNaija.com)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        btnPlay.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        btnPause.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnPause.setText("Stop");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });
        jPanel1.add(btnPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 0, 222));
        jLabel4.setText("AfroBeatz Category");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1284, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        musicPlayer("C:\\NetBeanProject\\Tutotrial\\src\\tutotrial\\02 Davido - FEEL (NetNaija.com).wav");
       
    }//GEN-LAST:event_btnPlayActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formComponentShown

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblPlaceOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlaceOrderMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new OrderMusic().setVisible(true);
    }//GEN-LAST:event_lblPlaceOrderMouseClicked

    private void lblViewOrderPlacedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewOrderPlacedMouseClicked
        // TODO add your handling code here:
         setVisible(false);
        new ViewSalesHistory().setVisible(true);
    }//GEN-LAST:event_lblViewOrderPlacedMouseClicked

    private void lblManageCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageCategoryMouseClicked
        // TODO add your handling code here:
         setVisible(false);
        new ManageCategory().setVisible(true);
    }//GEN-LAST:event_lblManageCategoryMouseClicked

    private void lblNewMusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewMusicMouseClicked
        // TODO add your handling code here:
         setVisible(false);
        new AddNewMusic().setVisible(true);
    }//GEN-LAST:event_lblNewMusicMouseClicked

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        // TODO add your handling code here:
        if(clip != null && clip.isRunning()){
            clip.stop();
        }
    }//GEN-LAST:event_btnPauseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard("raji@gmail.com").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblChangePassword;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblManageCategory;
    private javax.swing.JLabel lblNewMusic;
    private javax.swing.JLabel lblPlaceOrder;
    private javax.swing.JLabel lblViewOrderPlaced;
    // End of variables declaration//GEN-END:variables
}
